Ajout d'un système de rappels pour les parrains
DraftProducts/blagues-api pull request #194
Opened 2021-12-14 00:29 UTC by DraftProducts

2021-12-14 14:02 UTC, ErwanGit requested changes

2021-12-14 14:02 UTC, ErwanGit commented on src/bot/modules/reminders.ts
> +    schedule.scheduleJob('0 22 */2 * *', async () => {
Peut-être le mettre plus tôt ? Genre 21h ?
22h perso c'est vers l'heure ou j'y go et le lendemain, je vais cliquer sur la notif et je vais oublié

2021-12-14 14:02 UTC, ErwanGit commented on src/bot/modules/reminders.ts
> +      .filter((score) => score > 3)
Si je suis ton commentaire de 3 décisions au minimum
```suggestion
      .filter((score) => score >= 3)
```

2021-12-14 14:02 UTC, ErwanGit commented on src/bot/modules/reminders.ts
> +            footer: isLastPage ? { text: 'Blagues-API' } : undefined,
```suggestion
            footer: isLastPage ? { text: 'Blagues API' } : undefined,
```

2021-12-14 14:02 UTC, ErwanGit commented on src/bot/modules/reminders.ts
> +            title: isFirstPage ? 'Parrains du projet Blagues-API' : undefined,
```suggestion
            title: isFirstPage ? 'Parrains du projet Blagues API' : undefined,
```

2021-12-15 00:03 UTC, DraftProducts commented on src/bot/modules/reminders.ts
> +    schedule.scheduleJob('0 22 */2 * *', async () => {
Yes je suis d'accord 👍

2021-12-15 04:08 UTC, ErwanGit requested changes

2021-12-15 04:08 UTC, ErwanGit commented on src/bot/modules/reminders.ts
> +    // Every two days at 10 p.m.
```suggestion
    // Every two days at 9 p.m.
```

2021-12-15 14:22 UTC, ErwanGit approved these changes

2021-12-15 14:35 UTC, merged