Ajout du système d'approbations de suggestions avec corrections en attente
DraftProducts/blagues-api pull request #325
Opened 2022-06-18 16:28 UTC by DraftProducts

Closes: #243

2022-06-19 19:57 UTC, ErwanGit approved these changes

2022-06-21 15:58 UTC, ErwanGit approved these changes

2022-06-21 16:44 UTC, ErwanGit requested changes

2022-06-21 16:44 UTC, ErwanGit commented on src/bot/commands/approve.ts
> +          `Seul un <@${godfatherRoleId}> peut approuver une ${isSuggestion ? 'blague' : 'correction'}.`
```suggestion
          `Seul un <@&${godfatherRoleId}> peut approuver une ${isSuggestion ? 'blague' : 'correction'}.`
```

2022-06-22 13:22 UTC, ErwanGit approved these changes

2022-06-23 05:56 UTC, Swiizyy approved these changes

2022-06-23 17:21 UTC, ErwanGit approved these changes

2022-06-23 17:22 UTC, merged