Ajout de la suppressions du message (no proposal)
DraftProducts/blagues-api pull request #336
Opened 2022-06-20 23:41 UTC by Swiizyy

Closes: #335
- Ajout d'une fonction tDelete()
- Suppression des messages problem au bout de 5 secondes
- Améliorer la suppression du message (Aucune blague a été trouvée) avec la nouvelle fonction

2022-06-20 23:44 UTC, Swiizyy commented on src/bot/commands/correction.ts
> +        question.channel.send("Aucune blague n'a été trouvée, veuillez réessayer !").then(tDelete(5000));
Est-ce vraiment utile de laisser se message sachant qu'y en a un déjà dans la fonction **this.findJoke()** ?

2022-06-21 00:07 UTC, DraftProducts requested changes

2022-06-21 00:07 UTC, DraftProducts commented on src/bot/commands/correction.ts
> +          .then(tDelete(5000));
```suggestion
          .then(tDelete(10000));
```

2022-06-21 00:07 UTC, DraftProducts commented on src/bot/commands/correction.ts
> +        question.channel.send("Aucune blague n'a été trouvée, veuillez réessayer !").then(tDelete(5000));
Oui, t'as raison, ça fait doublon, mais à ce compte-là il faudrait en ajouter un L295.

Quelque chose comme : 
```js
`Impossible de trouver une blague à partir de ${idType === IdType.JOKE_ID ? 
	'cet identifiant' : 
	'cette question'
}, veuillez réessayer !`
```

2022-06-21 00:07 UTC, DraftProducts commented on src/bot/commands/correction.ts
> +              `Impossible de trouver une blague ou correction liée à cet ID de blague, assurez vous que cet ID provient bien d\'un message envoyé par le bot ${interaction.client.user}`
```suggestion
              `Impossible de trouver une blague ou correction liée à cet identifiant de message, assurez-vous que ce dernier provienne bien d\'un message envoyé par ${interaction.client.user}. Veuillez réessayer !`
```

2022-06-21 06:22 UTC, Swiizyy reviewed
Ok c'est good @DraftProducts

2022-06-21 07:19 UTC, DraftProducts requested changes

2022-06-21 07:19 UTC, DraftProducts commented on src/bot/commands/correction.ts
> +        question.channel.send("Aucune blague n'a été trouvée, veuillez réessayer !").then(tDelete(5000));
Faut la supprimer du coup nn ?
```suggestion
```

2022-06-21 07:24 UTC, Swiizyy reviewed
Ok c'est good

2022-06-21 07:26 UTC, DraftProducts approved these changes

2022-06-21 15:49 UTC, ErwanGit requested changes

2022-06-21 15:49 UTC, ErwanGit commented on src/bot/commands/correction.ts
> +          .then(tDelete(10000));
Pour la lecture
```suggestion
          .then(tDelete(10_000));
```

2022-06-21 16:41 UTC, merged