Change sticky messages system (actualy by timeout) for a messageCreate event system
DraftProducts/blagues-api pull request #352
Opened 2022-06-22 01:48 UTC by achille-bsc

ça permettra une optimisation du système ainsi qu'une meilleur fluiditée pour le message collant

2022-06-22 13:30 UTC, swiizyy commented on src/bot/index.ts
> +  }
Tu pourrais laisser tout sa dans son fichier de base je pense nan ?

2022-06-22 13:31 UTC, achille-bsc commented on src/bot/index.ts
> +  }
Oui, c'est vrai... la j'ai juste fais un premier jet direct dans l'évent... mais je pouraos changer ça quand j'aurais un peut de temps

2022-06-22 13:49 UTC, Swiizyy commented
@achille-bsc Tu peut faire une issues pour cette amélioration stp ?

2022-06-22 13:53 UTC, achille-bsc commented
> @achille-bsc Tu peut faire une issues pour cette amélioration stp ?

Bah, je sais pas faire... j'utilise sue très peut github... je ne sais même pas quelle est la différence entre une pr et une issue 😅

2022-06-22 13:55 UTC, achille-bsc commented
Enfaîte t'as juste retiré ce sue j'avais fais ?

2022-06-22 13:57 UTC, Swiizyy commented
Modifier pour le laissé dans sont fichier 👍🏼

2022-06-22 14:00 UTC, achille-bsc commented
> Modifier pour le laissé dans sont fichier 👍🏼 

Ah oui, j'avais pas tout review deso 😅 merci 👍 je l'aurais fais dans la soirée mais au moins la c'est fais 🙃 Merci

2022-06-22 18:33 UTC, ErwanGit requested changes
+ il faudrait retirer le fichier .DS_Store (ou le mettre en .gitignore)

2022-06-22 18:33 UTC, ErwanGit commented on src/bot/index.ts
> +    if (message.channelId != suggestionsChannelId && message.channelId != correctionsChannelId) return;
```suggestion
    if (message.channelId !== suggestionsChannelId && message.channelId !== correctionsChannelId) return;
```

2022-06-22 20:33 UTC, Swiizyy approved these changes

2022-06-22 23:30 UTC, DraftProducts requested changes

2022-06-22 23:30 UTC, DraftProducts commented on src/bot/index.ts
> +    if (message.channelId !== suggestionsChannelId && message.channelId !== correctionsChannelId) return;
```suggestion
    if (![suggestionsChannelId, correctionsChannelId].includes(message.channelId)) return;
```

2022-06-22 23:30 UTC, DraftProducts commented on src/bot/index.ts
> +    }
Utiliser un switch :v:

2022-06-22 23:30 UTC, DraftProducts commented on src/bot/modules/stickys.ts
>      if (process.env.bot_stickies === 'false') return;
À supprimer également.
```suggestion
```

2022-06-23 00:18 UTC, achille-bsc commented
> Et il faudrait retirer le fichier .DS_Store (ou le mettre en .gitignore)

c'est bon 👍 c'est ajouté au .gitignore

2022-06-23 00:37 UTC, DraftProducts requested changes

2022-06-23 00:37 UTC, DraftProducts commented on src/bot/index.ts
> +    }
```suggestion
    switch (message.channelId) {
      case suggestionsChannelId:
        this.stickys.sticky(suggestionsChannelId, this.stickys.suggestsMessage());
        break;
      case correctionsChannelId:
        this.stickys.sticky(correctionsChannelId, this.stickys.correctionsMessage());
        break;
      default: break;
    }
```

2022-06-23 00:47 UTC, DraftProducts approved these changes

2022-06-23 05:14 UTC, ErwanGit requested changes

2022-06-23 05:14 UTC, ErwanGit commented on src/bot/index.ts
> +        break;
```suggestion
        return this.stickys.sticky(suggestionsChannelId, this.stickys.suggestsMessage());
```

2022-06-23 05:14 UTC, ErwanGit commented on src/bot/index.ts
> +        break;
```suggestion
        return this.stickys.sticky(correctionsChannelId, this.stickys.correctionsMessage());
```

2022-06-23 05:14 UTC, ErwanGit commented on src/bot/index.ts
> +        break;
Je ne pense pas qu'il soit nécessaire vu qu'il y a pas de suite à cette fonction ici

2022-06-23 10:00 UTC, DraftProducts commented on src/bot/index.ts
> +        break;
Pour le coup, c'est plus parce qu'il n'y a pas d'autres options possibles.
Même s'il n'y a pas de suite, il faut un default s'il y a une chance que les cases actuelles ne résolvent toutes les valeurs possibles.

2022-06-23 13:18 UTC, DraftProducts approved these changes

2022-06-23 15:21 UTC, ErwanGit commented
Cette PR est ouverte ou fermée (même question concernant #359) ?

2022-06-23 15:30 UTC, DraftProducts commented
Le fork a été supprimé, ça les a fermé automatiquement.

2022-06-23 15:41 UTC, ErwanGit approved these changes

2022-06-23 15:46 UTC, merged