Enlever le contenu et composants du message (success suggest)
DraftProducts/blagues-api pull request #353
Opened 2022-06-22 13:05 UTC by Swiizyy

2022-06-22 13:20 UTC, ErwanGit approved these changes

2022-06-22 23:25 UTC, DraftProducts requested changes

2022-06-22 23:25 UTC, DraftProducts commented on src/bot/commands/suggest.ts
> +    return confirmation.update({
Je ne sais pas ce que t'en pense, mais j'aurais plus opté pour une édition de la fonction `interactionValidate` pour ajouter un paramètre éphémère optionnel avec comme valeur par défaut `true`.
Comme ça tu peux faire directement :
```js
return confirmation.update(interactionValidate(`La [blague](${suggestion.url}) a été envoyé !`), false);
```

2022-06-23 07:37 UTC, Swiizyy commented on src/bot/commands/suggest.ts
> +    return confirmation.update({
C'est se que je voulais mais j'y arrive pas les types bloques toujours ... 🤔

2022-06-23 13:52 UTC, DraftProducts approved these changes

2022-06-23 15:22 UTC, ErwanGit approved these changes

2022-06-23 15:29 UTC, merged