Refonte du système de statistiques
DraftProducts/blagues-api pull request #370
Opened 2022-06-24 01:01 UTC by saphirrc

Pour le nouveau système de statistiques, il est prévu de donner plus ou moins de points en fonction de l'appréciation de la blague. Chaque action donne un certain nombre de points. 

Closes: #198 

### Système de points

| Action      | Points      |
|------------|-----------|
| Proposition d'une blague | +10 points |
| Correction d'une blague | +7 points |
| Approbation d'une blague* | +4 points |
| Désapprobation d'une blague* | +4 points |
| Vote d'une blague via une réaction** | +2 points |

\* Points pour l'approbation d'une blague pour un parrain.
\*\* Les votes via réactions ne seront pas comptabilisés pour les parrains.

**Points bonus :**
| Action      | Points      |
|------------|-----------|
| Approbation d'un parrain | +2 points |
| Désapprobation d'un parrain | -2 points  |
| Vote d'un membre positif | +1 point |
| Vote d'un membre négatif | -1 point  |

---
### Roadmap :

- [ ] Design du message
- [ ] Adaptation de la base de données pour le stockage des statistiques de réactions.
- [ ] Statistiques calculées à partir des blagues & corrections.
- [ ] Statistiques calculées à partir des votes des parrains.
- [ ] Statistiques calculées à partir des votes via réactions.
- [ ] Statistiques bonus d'appréciation de la blague
- [ ] Statistiques total

2022-07-06 20:45 UTC, DraftProducts commented
Salut @Swiizyy, @achille-bsc.
@saphirrc nous a fait part qu'il manquait de temps pour s'en occuper.
Si cette feature chauffe l'un d'entre vous, je peux vous assigner la PR ✌️

2022-07-06 21:20 UTC, achille-bsc commented
> Salut @Swiizyy, @achille-bsc.
> @saphirrc nous a fait part qu'il manquait de temps pour s'en occuper.
> Si cette feature chauffe l'un d'entre vous, je peux vous assigner la PR ✌️ 

Hum.... moi ça m'intéresserais grave ! Mais par contre je n'ai aucune idée de comment faire ça ! Tout ce qui est de gérer la db et tour je ne sais pas du tout faire 😅

2022-07-07 09:58 UTC, DraftProducts requested changes

2022-07-07 09:58 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +      });
Afin d'éviter de spam les requêtes, il faudrait utiliser le `include` dans la requête de base, tu pourras ainsi les récupérer avec `suggestion.approvals`.
n'hésite pas à regarder à d'autres endroits, on l'a fait plein de fois :v:

```ts
const proposals = await prisma.proposal.findMany({
  where: {
    user_id: member.id,
    stale: false,
  },
  include: {
    approvals: true,
    disapprovals: true,
  }
});
```

2022-07-07 09:58 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +  static async getPoints(member: GuildMember): Promise<number> {
Tout compte fait, je pense qu'on pourrait donner des points aux corrections qui sont notés comme stale pour la volonté de l'avoir fait, quelque chose comme 3 points ? 🤔

2022-07-07 09:58 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +  static async getPoints(member: GuildMember): Promise<number> {
Pour ce qui est des approbations des parrains, il te suffit de compter combien de fois l'utilisateur ciblé est dans les approvals & disapprovals.
Je pense que tu peux même le faire à partir de `proposals` directement pas besoin de passer par suggestions & corrections.

2022-07-07 09:58 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +  static async getPoints(member: GuildMember): Promise<number> {
Pour ce qui est des votes tu peux les récupérer aussi via un include (voir le commentaire qui en parle) il me semble que c'est.

2022-07-07 09:58 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +      if (suggestion.merged) userPoints += 10;
Attention, n'oublie pas que les points bonus sont là uniquement lorsque la blague a été merge.

2022-07-08 08:26 UTC, DraftProducts requested changes

2022-07-08 08:26 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +      if (proposal.stale === true) userPoints += 5;
```suggestion
      if (proposal.stale) userPoints += 5;
```

2022-07-08 08:26 UTC, DraftProducts commented on src/bot/modules/stats.ts
>      const [suggestions, corrections] = partition(proposals, (proposal) => proposal.type === ProposalType.SUGGESTION);
```suggestion
```

2022-07-08 08:26 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +    userPoints += this.proposalPoint(suggestions, false);
Étant donné qu'il n'y a pas besoin de les traiter séparément, je serais pour exploser la fonction et mettre le contenu directement ici.

2022-07-08 08:26 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +        userPoints += correction ? 7 : 10;
```suggestion
        userPoints += proposal.type === ProposalType.SUGGESTION ? 10 : 7;
```

2022-07-08 11:49 UTC, DraftProducts approved these changes
Nickel ✌️

2022-07-08 11:49 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +  static async getPoints(interaction: CommandInteraction<'cached'>, userID: Snowflake): Promise<number> {
```suggestion
  static async getPoints(interaction: CommandInteraction<'cached'>, userId: Snowflake): Promise<number> {
```

2022-07-08 12:09 UTC, Swiizyy commented
Plus qu'a trouver comment réglé sa 😬
![Capture](https://user-images.githubusercontent.com/52933626/177989252-2bc06406-a58d-4bc5-a290-d9fceb5b4af0.PNG)

2022-07-10 16:27 UTC, DraftProducts approved these changes

2022-07-18 23:56 UTC, DraftProducts commented
C'"est corrigé, mais je suis pas fan d'avoir une requête par utilisateur, il faudrait trouver un moyen pour n'avoir qu'une ou deux requêtes.

2022-07-19 11:46 UTC, achille-bsc approved these changes

2022-07-19 11:58 UTC, Swiizyy commented on src/bot/modules/stats.ts
> +    userPoints += votes.length * 2;
Il faut pas verifier si il n'est pas parrain ?

2022-07-19 12:25 UTC, Swiizyy commented on src/bot/modules/stats.ts
> +    userPoints += votes.length * 2;
```suggestion
    userPoints += !isParrain(member) ? votes.length * 2 : 0;
```

2022-07-19 12:25 UTC, Swiizyy commented on src/bot/modules/stats.ts
> +      return `<@${userId}> : ${points}}`;
```suggestion
    const membersPoints = membersIds.map(async (userId) => {
      const member = interaction.guild.members.cache.get(userId)!;

      const memberProposals = membersProposals.filter((p) => p.user_id === userId);
      const memberVotes = membersVotes.filter((v) => v.user_id === userId);

      const points = await this.calculatePoints(member, memberProposals, memberVotes, godfathersDecisions);

      return `<@${userId}> : ${points} ${points !== 1 ? 'points' : 'point'}`;
```

2022-07-19 12:36 UTC, Swiizyy requested changes
Vérifier si le membre n'est pas parrain pour les votes
Ajouts de 'point' ou 'point' après le nombre

2022-07-19 13:02 UTC, Swiizyy requested changes

2022-07-19 13:02 UTC, Swiizyy commented on src/bot/modules/stats.ts
> +    userPoints += votes.length * 2;
```suggestion
    } else {
      userPoints += votes.length * 2;
    }
```

2022-07-19 13:35 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +    userPoints += votes.length * 2;
Justement je l'ai retiré, c'est con qu'on gars qui passe parrain perdes ses points, je pense qu'il faudrait juste les bloquer au niveau de l'ajout.
Ou sinon mieux laisser le choix au parrain 🤔
En fonction du type de blague je sais que certains préfèrent juste voter. Peut être juste retirer le vote lors d'une approbation et empêcher le vote si il a une approbation.

2022-07-19 13:36 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +      return `<@${userId}> : ${points}}`;
Pourquoi voudrais tu await, cette fonction n'est pas async 🤔

2022-07-19 13:58 UTC, Swiizyy commented on src/bot/modules/stats.ts
> +      return `<@${userId}> : ${points}}`;
Pour ca et si si cette fonction est async 
`This condition will always return 'true' since the types 'Promise<number>' and '1' have no overlap.`

2022-07-19 14:02 UTC, Swiizyy commented on src/bot/modules/stats.ts
> +    userPoints += votes.length * 2;
J'approuve ta deuxieme idée a 100%

2022-07-19 14:15 UTC, Swiizyy requested changes

2022-07-19 14:17 UTC, Swiizyy commented on src/bot/modules/stats.ts
> +      return `<@${userId}> : ${points}}`;
Ok je viens de modifier tu a laissez un async en trop a la fonction `calculatePoints`

2022-07-19 14:19 UTC, Swiizyy requested changes

2022-07-19 14:19 UTC, Swiizyy commented on src/bot/modules/stats.ts
> +  ): Promise<number> {
```suggestion
  static calculatePoints(
    member: GuildMember,
    proposals: MemberProposal[],
    votes: Vote[],
    decisions: GodfathersDecisions
  ): number {
```

2022-07-19 18:22 UTC, ErwanGit commented on src/bot/modules/stats.ts
> +      if (proposal.refused) userPoints += 3;
Peut être pas compris mais c'est normal qui gagne des points positifs si c'est refusé ?

2022-07-19 18:22 UTC, ErwanGit commented on src/bot/modules/stats.ts
> +      if (proposal.stale) userPoints += 5;
Il gagne des points si c'est en cours ?

2022-07-19 18:37 UTC, Swiizyy commented on src/bot/modules/stats.ts
> +      if (proposal.refused) userPoints += 3;
Oui c'est normal et pour le stale aussi mais beaucoup moins que si elle est merge

2022-07-19 20:29 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +      if (proposal.refused) userPoints += 3;
Oui, même si sa blague est refusée finira par en perdre à cause des mauvais votes et désapprobations, mais ces points sont là pour saluer sa volonté de participer.
Ils atténueront les points manuls.

2022-07-19 20:30 UTC, DraftProducts commented on src/bot/modules/stats.ts
> +      if (proposal.stale) userPoints += 5;
Stale est là si la correction a été re-travaillé (quand on re-modifie une correction)

2022-07-19 21:03 UTC, achille-bsc commented on src/bot/commands/correction.ts
> +  upReactionIdentifier
Je propose de mettre upReactionIdentifier juste au dessu du downReactionIdentifier pour plus de cohérence dans l'ordre d'appelation des données

2022-07-19 21:12 UTC, Swiizyy approved these changes
Tout est bon pour moi.
Je vois juste une question à se poser étant donné qu'on supprime les réactions après avec merge ou refuser une proposition les nombres de votes vont être très limité.
Sachant que les votes dépendront de la rapidité des parrains a approuvé ou non la proposition, est-ce bien de laisser cela comme-ci ?

2022-07-19 21:17 UTC, Swiizyy commented on src/bot/commands/correction.ts
> +  upReactionIdentifier
@achille-bsc l'ordre se fait avec l'ordre alphabétique donc je pense que laissez comme ceci est tout aussi bien

2022-07-19 21:55 UTC, DraftProducts commented
Si on décide de laisser les votes ainsi que les utilisateurs voter même après que la proposition a eu son verdict, je pense qu'il faudrait diminuer la valeur en points 🤔

2022-07-19 22:07 UTC, achille-bsc commented on src/bot/modules/votes.ts
> +    const channel = reaction.message.channel as GuildTextBasedChannel;
Pourquoi ne pas définir la constante message juste avant cette ligne, pour pouvoir l'appeler directement à l'assignation de celle-ci ? Ce serait peut-être un peut plus propre non ?

2022-07-19 22:09 UTC, achille-bsc commented on src/bot/modules/votes.ts
> +    const channel = reaction.message.channel as GuildTextBasedChannel;
Pourquoi pas définir la variable message juste au dessus pour que on puisse définir channel de cette façon ?
```suggestion
    const channel = message.channel as GuildTextBasedChannel;
```

2022-07-19 22:44 UTC, swiizyy commented
Oui d'où la grosse réflexion de quelle côté se pencher ...

Mais personnellement je penche plus du coter de laisser telle qu'elle..

2022-07-19 22:45 UTC, Swiizyy commented on src/bot/modules/votes.ts
> +    const channel = reaction.message.channel as GuildTextBasedChannel;
Je pense que cela est inutile, le code est assez lisible comme ça

2022-07-20 00:13 UTC, DraftProducts commented on src/bot/modules/votes.ts
> +    const channel = reaction.message.channel as GuildTextBasedChannel;
Je vois pas non plus l'intérêt.
Le path d'accès n'est pas suffisamment long pour que ça soit intéressant.

2022-07-20 00:15 UTC, DraftProducts commented on src/bot/commands/correction.ts
> +  upReactionIdentifier
Pour le coup là aussi, c'est vraiment pas important du tout 😕

2022-07-20 06:25 UTC, Swiizyy commented
Pour les statistiques en fonction du temps on le fait toujours ou pas car je le vois plus sur le dash de la pr ?

2022-07-20 11:33 UTC, achille-bsc commented on src/bot/commands/correction.ts
> +  upReactionIdentifier
ouais, c'est pas hyper important... mais c'est juste que je trouvais ça un peut bête de déclarer une variable ici alors qu'elle pourais être utilisée dès la ligne du dessus 😅

2022-07-20 11:55 UTC, DraftProducts commented
Yes on peut faire un truc comme ça 👍

2022-07-20 11:59 UTC, DraftProducts approved these changes

2022-07-20 12:37 UTC, Swiizyy commented
Je vois ce que tu veux dire... Dans ce cas, si on veut l'intégrer, il faudrait rajouter un paramètre `created_at` aux approvals | disapprovals.

Que pensez-vous  de rajouter cela et d'afficher les statistiques en fonction du temps ?

2022-07-20 13:27 UTC, DraftProducts commented
Je pense qu'on pourra ajouter ça à l'avenir dans une nouvelle PR, pour l'instant, je ne suis pas trop motivé surtout qu'il faudra surement rééquilibrer l'attribution des points.
Je propose déjà de merge cette PR qui est ouverte depuis un mois.

2022-07-20 13:51 UTC, swiizyy approved these changes
D'accord. C'est bon pour moi.

2022-07-21 07:30 UTC, ErwanGit approved these changes

2022-07-21 10:09 UTC, merged