Button reminder
DraftProducts/blagues-api pull request #373
Opened 2022-06-24 11:53 UTC by achille-bsc

2022-06-24 12:10 UTC, DraftProducts requested changes

2022-06-24 12:10 UTC, DraftProducts commented on src/bot/index.ts
>      }
```suggestion
    }
    
    if (interaction.isButton() && interaction.customId === 'user_reminder') {
      return this.reminders.pendingUserReminders(interaction);
    }
```

2022-06-24 15:47 UTC, DraftProducts approved these changes

2022-06-25 01:30 UTC, DraftProducts requested changes

2022-06-25 01:30 UTC, DraftProducts commented on src/bot/modules/reminders.ts
> +          : '';
```suggestion
       if (
         proposal.approvals.map((m) => m.user_id).includes(`${interaction.user.id}`) ||
         proposal.disapprovals.map((m) => m.user_id).includes(`${interaction.user.id}`) ||
         proposal.user_id === interaction.user.id
        ) {
            return acc;
        }
        const line = `[${ProposalType.SUGGESTION ? 'Suggestion' : 'Correction'}](${messageLink(
            guild.id,
            proposal.type === ProposalType.SUGGESTION ? suggestionsChannelId : correctionsChannelId,
            proposal.message_id!
        )}) (${Math.max(proposal.approvals.length, proposal.disapprovals.length)}/${neededApprovalsCount})\n`;
```

2022-06-25 01:30 UTC, DraftProducts commented on src/bot/modules/reminders.ts
> +      await interaction.reply({
```suggestion
      await interaction[interaction.replied ? 'editReply' : 'reply']({
```

2022-06-25 01:30 UTC, DraftProducts commented on src/bot/modules/reminders.ts
> +            description: pages[index] || 'Aucune Propsitions',
```suggestion
            description: pages[index] || 'Aucune propsition',
```

2022-06-25 21:31 UTC, DraftProducts approved these changes

2022-06-25 21:31 UTC, merged

2022-06-26 12:53 UTC, Swiizyy commented
@DraftProducts tu aurais pas du merge le code ne fonctionne pas apres les modifs que tu ma fait faire ... 😕😕