Ajout de la commande report
DraftProducts/blagues-api pull request #412
Opened 2022-08-03 09:36 UTC by Swiizyy

Closes: #377

2022-08-03 10:16 UTC, DraftProducts commented
Bien que je comprennes pas comment c'est possible, il semblerait que tu ais commit des fichiers du dossier node_modules.
Ils seront à supprimer.

2022-08-03 10:21 UTC, Swiizyy commented
Ça doit être @MrPRAINGLE qui la commit 😬

2022-08-03 12:36 UTC, MrPRAINGLE commented
Voui c'est moi... Oké je supprime (pour la ptite explication, j'ai modifié le gitignore sans le commit et comme ça j'ai pu commit le fichier de prisma)

2022-08-03 13:39 UTC, DraftProducts commented
T'es pas sensé modifier le gitignore 🤔

2022-08-06 09:55 UTC, MrPRAINGLE commented
J'avais pas compris comment bidouiller prisma du coup j'ai changer le fichier node_modules :sweat_smile: 
Désolé

2022-08-08 20:49 UTC, ErwanGit requested changes

2022-08-08 20:49 UTC, ErwanGit commented on src/bot/commands/approve.ts
> +          `Vous ne pouvez pas approuver une blague, une correction ou un signalement en dehors des salons <#${suggestionsChannelId}>, <#${correctionsChannelId}> et <"${reportsChannelId}>.`
```suggestion
          `Vous ne pouvez pas approuver une blague, une correction ou un signalement en dehors des salons <#${suggestionsChannelId}>, <#${correctionsChannelId}> et <#${reportsChannelId}>.`
```

2022-08-08 20:49 UTC, ErwanGit commented on src/bot/commands/approve.ts
> +        content: "Blague ajoutée à l'API",
À confirmer
```suggestion
        content: "Blague retirée à l'API",
```

2022-08-08 20:49 UTC, ErwanGit commented on src/bot/commands/disapprove.ts
> +          `Vous ne pouvez pas désapprouver une blague, une correction ou un signalement en dehors des salons <#${suggestionsChannelId}>, <#${correctionsChannelId}> et <"${reportsChannelId}>.`
```suggestion
          `Vous ne pouvez pas désapprouver une blague, une correction ou un signalement en dehors des salons <#${suggestionsChannelId}>, <#${correctionsChannelId}> et <#${reportsChannelId}>.`
```

2022-08-08 20:49 UTC, ErwanGit commented on src/bot/utils.ts
> +    } ?`,
Plus propre comme ça
```suggestion
    content: `Êtes-vous sûr de vouloir confirmer la proposition de ${
      sendType === 'report' ? 'ce signalement' : 'cette blague'
    } ?`,
```

2022-08-08 20:49 UTC, ErwanGit commented on src/jokes.ts
> +      console.log('Missing access', error);
```suggestion
      console.error('Missing access', error);
```

2022-08-08 20:49 UTC, ErwanGit commented on src/jokes.ts
> +      return { success: false, error: `Il semblerait que le fichier de blagues soit inaccessible ou innexistant.` };
```suggestion
      return { success: false, error: 'Il semblerait que le fichier de blagues soit inaccessible ou inexistant.' };
```

2022-08-08 20:49 UTC, ErwanGit commented on src/jokes.ts
> +      console.log('Error:', error);
```suggestion
      console.error('Error:', error);
```

2022-08-09 10:12 UTC, Swiizyy commented
:warning: Attention je n'est pas encore fait les modifs pour la commande desaprouve !!

2022-08-09 16:36 UTC, DraftProducts requested changes

2022-08-09 16:36 UTC, DraftProducts commented on prisma/migrations/20220809092340_report_commands/migration.sql
> +CREATE UNIQUE INDEX "proposals_suggestion_id_key" ON "proposals"("suggestion_id");
Comme indiqué dans le commentaire du haut, c'est pas possible, il faudrait reset la DB surtout qu'en plus on peut avoir plusieurs proposals (corrections & corrections) avec le même id.

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +}
Pourquoi avoir fait ça quand 5 arguments dont le dernier optionel aurait suffit ?

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +    })) as Exclude<Proposals, ReportExtended> | null;
Si tu as besoin de faire un `as` après une requête de prisma, c'est que tu demandes dans ta requête des choses dont tu n'as pas besoin et que tu n'utilises pas (selon ton typage)

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +      const newembed = await updateProposalsEmbed(interaction, proposal, embed);
Généralement on préfère dire oldVariable et variable plutôt que variable et newVariable.
Ça permet de savoir à l'avance qu'elle va être remplacé et qu'elle est là juste pour être consommée.

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +    const { interaction, message } = options;
```suggestion
  async proposalsCollector({ interaction, message }: CollectorOptions) {
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +        message_id: options.message.id
```suggestion
        message_id: message.id
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +          id: proposal.id!
id n'est pas optionel (coucou le typage forcé qui est faux)
```suggestion
          id: proposal.id
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +          const suggestionLink = messageLink(interaction.guild!.id, suggestionsChannelId, proposal.message_id!);
Etant donné que le typage 'cached' est bon, guild n'est normalement pas optionel
```suggestion
          const correctionLink = messageLink(interaction.guild.id, correctionsChannelId, correction.message_id!);
          const suggestionLink = messageLink(interaction.guild.id, suggestionsChannelId, proposal.message_id!);
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +    const { interaction, message } = options;
```suggestion
  async reportCollector({ interaction, message }: CollectorOptions) {
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +    })) as ReportExtended | null;
Pareil pas de forçage de typage ici

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +      await message.edit({ embeds: [newembed] });
Pareil (mauvais nom)

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +      await prisma.report.update({
Pourquoi tu push un report dans les approvals ?

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
>          }
Sûr d'en avoir besoin ?

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +    const newembed = await updateProposalsEmbed(interaction, proposal, embed);
Pareil mauvais nom

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +  async approveSuggestion(options: ApproveOptions<Suggestion> & { automerge?: boolean }): Promise<void> {
Déjà inclu dans le typage de ApproveOptions
```suggestion
  async approveSuggestion(options: ApproveOptions<Suggestion>): Promise<void> {
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +  async approveSuggestion(options: ApproveOptions<Suggestion> & { automerge?: boolean }): Promise<void> {
Options à inclure directement
```suggestion
  async approveSuggestion({ interaction, proposal, message, embed, automerge }: ApproveOptions<Suggestion>): Promise<void> {
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +    const { interaction, proposal, message, embed, automerge } = options;
```suggestion
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +    await message.client.stickys.reload();
Bien que ce soit asynchrone c'est très lourd en terme de fonctionnement donc on préfère l'executer dans un thread différent (donc sans await) 
```suggestion
    message.client.stickys.reload();
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +    const { interaction, proposal, message, embed } = options;
```suggestion
  async approveReport({ interaction, proposal, message, embed }: ApproveOptions<ReportExtended>): Promise<void> {
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +    await message.client.stickys.reload();
Pareil

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +    const { interaction, proposal, message, embed } = options;
```suggestion
  async approveCorrection({ interaction, proposal, message, embed }: ApproveOptions<Correction>): Promise<void> {
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +        proposal: proposal.suggestion as Suggestion,
Pas nécessaire vu que t'as un typage paramétré pour les options du approveSuggestion
```suggestion
        proposal: proposal.suggestion,
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/disapprove.ts
> +      }
Y'a un souci ici mais je pense que c'est parce que t'as pas finit 🤔

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/disapprove.ts
> +    const newembed = await updateProposalsEmbed(interaction, proposal, embed);
Pareil mauvais nom

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/report.ts
> +            name: name.toLowerCase(),
Pas convaincu par ça, soit tu laisses un ReasonsRefs, soit tu l'écris à la mano, parce qu'une enum c'est sans accents et avec un lowercase ça met tout en minuscule, même la première lettre.

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/report.ts
> +    if (isAlreadyReport.filter((p) => p.reports).length > 0) {
```suggestion
    if (isAlreadyReport.filter((p) => p.reports).length) {
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/commands/report.ts
> +        value: ReportType[reason].toLowerCase(),
Pareil qu'en haut

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/utils.ts
> +  })) as Message<true>;
Si tu reçois un `Message` et non un `Message<true>` c'est pas pour rien.

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/utils.ts
> +export async function updateProposalsEmbed(
*pense à utiliser F2*
```suggestion
export async function updateProposalEmbed(
```

2022-08-09 16:36 UTC, DraftProducts commented on src/bot/utils.ts
> +export async function checkProposalsifMergeOrRefused(
Atchoum !
```suggestion
export async function checkProposalStatus(
```

2022-08-09 16:36 UTC, DraftProducts commented on src/typings.ts
> +};
```suggestion
interface GodfathersDecisions {
  approvals: Approval[];
  disapprovals: Disapproval[];
}

export interface ReportExtended extends Report, GodfathersDecisions {
  suggestion: Suggestion;
};
```
Pense également à utiliser le typage `GodfathersDecisions` dans `ProposalExtended`
```ts
export type ProposalExtended = Proposal & GodfathersDecisions;
```

2022-08-10 16:44 UTC, DraftProducts requested changes

2022-08-10 16:44 UTC, DraftProducts commented on src/typings.ts
> +};
```suggestion
export const Reasons: Record<ReportType, string> = {
  [ReportType.DUPLICATE]: 'Doublon',
  [ReportType.INAPPROPRIATE]: 'Inappropriée'
};
```

2022-08-10 16:44 UTC, DraftProducts commented on src/typings.ts
> +}
Y'a pas de raison que Report prenne un S, c'est un typage c'est un singulier.
```suggestion
export interface ReportExtended extends Report, GodfathersDecisions {
  suggestion: Suggestion;
}
```

2022-08-10 16:44 UTC, DraftProducts commented on src/jokes.ts
> +    proposal: Exclude<Proposals, ReportExtended>
À éviter ce genre d'exclusion en dehors d'un type nommé.
Surtout que ça n'a pas de sens de voir ReportExtended dans le type Proposals vu que s'en est pas un.

2022-08-10 16:44 UTC, DraftProducts commented on src/bot/commands/disapprove.ts
> +      const newembed = await updateProposalEmbed(interaction, proposal, embed);
Nom toujours pas bon 👀

2022-08-10 18:18 UTC, Swiizyy commented on src/bot/commands/disapprove.ts
> +      const newembed = await updateProposalEmbed(interaction, proposal, embed);
@DraftProducts C'est normale j'ai pas encore toucher à la commande désapprouve 👀

2022-08-11 13:21 UTC, DraftProducts requested changes
Beaucoup de chipotage mais c'est essenciel pour une bonne lisibilité et un code propre.

2022-08-11 13:21 UTC, DraftProducts commented on src/bot/commands/report.ts
> +    if (reason === Reasons.DUPLICATE) {
```suggestion
    if (reason === ReasonType.DUPLICATE) {
```

2022-08-11 13:21 UTC, DraftProducts commented on src/jokes.ts
> +  public async mergeJoke(proposal: Proposals): Promise<{ success: boolean; joke_id?: number; error?: string }> {
Je pense que ce serait mieux de sortir ce typage de la promesse et d'en faire une interface dans le même fichier, genre `MergeJokeResponse`

2022-08-11 13:21 UTC, DraftProducts commented on src/typings.ts
> +export type Proposals = Correction | Suggestion;
Peut-être que si tu n'as que ces deux types, ça sera plus propre de les indiquer directement.

2022-08-11 13:21 UTC, DraftProducts commented on src/typings.ts
> +
```suggestion
```

2022-08-11 13:21 UTC, DraftProducts commented on src/bot/commands/report.ts
> +    const reason = interaction.options.getString('raison', true) as keyof typeof Reasons;
```suggestion
    const reason = interaction.options.getString('raison', true) as ReportType;
```

2022-08-11 13:21 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +                approvals: true
```suggestion
                approvals: true,
                disapprovals: true
```

2022-08-11 13:45 UTC, swiizyy commented
Tkt pas je comprends 🙂
Je vais essayer de faire la commande désapprouve se soir si je suis pas trop crevé par cette grosse chaleur 🥵

2022-08-13 12:38 UTC, DraftProducts requested changes

2022-08-13 12:38 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +  proposal: T extends Correction ? Correction : T extends Suggestion ? Suggestion : ReportExtended;
Je crois pas que ça serve à quelque chose 🤔

2022-08-13 12:38 UTC, DraftProducts commented on src/bot/utils.ts
> +export interface ApproveOptions<T extends Correction | Suggestion | ReportExtended> {
Tu tu le créé ici, ça vaut peut être le coup de l'utiliser dans les autres fichiers et supprimer ceux que tu as dedans :v:

2022-08-13 13:06 UTC, Swiizyy commented on src/bot/commands/approve.ts
> +  proposal: T extends Correction ? Correction : T extends Suggestion ? Suggestion : ReportExtended;
Si je le met pas j'ai sa comme erreur :/
```bash
Type '{ [x: string]: (({ interaction, proposal, message, embed, automerge }: ApproveOptions<Suggestion>) => Promise<void>) | (({ interaction, proposal, message, embed }: ApproveOptions<Correction>) => Promise<void>) | (({ interaction, proposal, message, embed }: ApproveOptions<...>) => Promise<...>); }' is not assignable to type 'Record<string, (options: ApproveOptions<Correction | Suggestion | ReportExtended>) => Promise<void>>'.
  'string' index signatures are incompatible.
    Type '(({ interaction, proposal, message, embed, automerge }: ApproveOptions<Suggestion>) => Promise<void>) | (({ interaction, proposal, message, embed }: ApproveOptions<Correction>) => Promise<void>) | (({ interaction, proposal, message, embed }: ApproveOptions<...>) => Promise<...>)' is not assignable to type '(options: ApproveOptions<Correction | Suggestion | ReportExtended>) => Promise<void>'.
      Type '({ interaction, proposal, message, embed, automerge }: ApproveOptions<Suggestion>) => Promise<void>' is not assignable to type '(options: ApproveOptions<Correction | Suggestion | ReportExtended>) => Promise<void>'.
        Types of parameters '__0' and 'options' are incompatible.
          Type 'ApproveOptions<Correction | Suggestion | ReportExtended>' is not assignable to type 'ApproveOptions<Suggestion>'.
            Type 'Correction | Suggestion | ReportExtended' is not assignable to type 'Suggestion'.
              Type 'Correction' is not assignable to type 'Suggestion'.
                Property 'corrections' is missing in type 'Correction' but required in type '{ type: "SUGGESTION"; corrections: ProposalExtended[]; }'.
```

2022-08-13 13:22 UTC, Swiizyy commented on src/bot/utils.ts
> +export interface ApproveOptions<T extends Correction | Suggestion | ReportExtended> {
Bien vu, c'était juste un oublie quand j'ai transféré les collectors dans utils pour car je vais les utiliser pour le désapprouve :)

2022-09-10 10:12 UTC, DraftProducts commented
Superseded by #424

2022-09-10 10:12 UTC, closed without merging