Pouvoir ignorer des types de blagues en tant que parrain
DraftProducts/blagues-api pull request #416
Opened 2022-08-15 16:04 UTC by Swiizyy

2022-08-16 08:26 UTC, DraftProducts requested changes

2022-08-16 08:26 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +    // TODO: Refactor le bloc de code pour check le salon commande dans une fonction
Il faudra pull la branche dev une fois la PR #417 merge.

2022-08-16 08:26 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +    }
Il y a une fonction pour check si un membre est parrain, ce serait mieux de l'utiliser étant donné qu'on peut être parrain sans avoir sa ligne d'émoji.
Compte tenu que ça créé pleins de problèmes si on a pas de ligne je propose de faire deux messages. 

```ts
if (!isGodfather(interaction.member)) {
    return interaction.reply(interactionInfo('Seul les parrains peuvent utiliser cette commande.'));
}
if (!godfather) {
    return interaction.reply(interactionInfo('Veuillez approuver plusieurs blagues avant de faire la fine bouche ! 😜'));
}
```

2022-08-16 08:26 UTC, DraftProducts commented on prisma/schema.prisma
> +  ignored_categories String[]
```suggestion
  ignored_categories String[] @db.VarChar(255)
```

2022-08-16 08:26 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +        `Vous avez ${isAlreadyIgnored ? 'dé-ignoré' : 'ignoré'} la catégorie \`${
```suggestion
        `Vous avez ${isAlreadyIgnored ? 'désignoré' : 'ignoré'} la catégorie \`${
```

2022-08-16 22:55 UTC, DraftProducts requested changes

2022-08-16 22:55 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +  private static ActionButtonsMapping: Record<string, string> = {
Je pense qu'il n'y a pas besoin de la déclarer dans la class, on peut la déclarer en dehors du scope

2022-08-16 22:55 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +    })) as unknown as Message<true>;
Le reply d'une interaction est une réponse de message de webhook donc tu n'as aucune donnée de cache, le typage de Discord.js qui est Message est bon 🤔

2022-08-16 22:55 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +    while (true) {
Ça, c'est interdit 😬 Il faudrait en effet essayer de le refactor 👍

2022-08-16 22:55 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +    } as InteractionReplyOptions;
Pas de raison de forcer le type
```suggestion
    };
```

2022-08-16 22:55 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +    return godfather as MinimalGodfatherPayload;
Pareil

2022-08-16 22:55 UTC, DraftProducts commented on src/bot/utils.ts
> +export async function interactionWaiter<T extends WaitForInteractionOptions<MessageComponentType>>(
Le message devrait être un paramètre indépendant et obligatoire.
Il ne devrait pas être présent dans les options.
Quelque chose comme ça : `waitForInteraction(message, options)` avec une fusion des options actuelles.

2022-08-16 22:55 UTC, DraftProducts commented on src/bot/utils.ts
> +        }
```suggestion
        if (reject_on_idle || reason !== 'idle') {
          return reject(reason);
        }
```

2022-08-16 22:55 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +  private async checkIsGodfather(interaction: ChatInputCommandInteraction<'cached'>): Promise<MinimalGodfatherPayload> {
Je suis pas convaincu par l'utilisation d'une fonction ici 🤔 
Ce serait plus simple et plus propre de garder le code procédural qu'on avait avant.
- Pas de gestion d'erreurs
- Pas de forçage ou de création de typage
- Meilleur lecture du code

2022-08-16 22:55 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +    const buttonsRows = [buttons.slice(0, 3), buttons.slice(3)];
Un petit reduce pour la réduction de la liste je dirais 🤔 
Ce type de bidouille est pas consistant

2022-08-16 22:55 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +    const embed = info('Choisissez quels catégories vous souhaitez ignorer / voir à nouveau');
Pas de raison que ce soit déclaré aussi haut dans le scope, il peut directement être intégré au payload

2022-08-17 09:19 UTC, Swiizyy commented on src/bot/utils.ts
> +export async function interactionWaiter<T extends WaitForInteractionOptions<MessageComponentType>>(
Les seules options **non obligatoire** actuelement sont `time` et `delete`  je ne vois qonc pas pk le bouger de place :/

2022-08-17 09:33 UTC, Swiizyy commented on src/bot/utils.ts
> +export function error(message: string): APIEmbed {
Pk en refaire alors qu'il en existe déja ?

2022-08-17 09:33 UTC, Swiizyy commented on src/bot/commands/ignore.ts
> +      godfather = await this.checkIsGodfather(interaction);
Pk ne pas utilisé IsGodfather ?

2022-08-21 13:06 UTC, Zuruuh commented on src/bot/commands/ignore.ts
> +    return godfather as MinimalGodfatherPayload;
Ici le field `ignored_categories` de godfather est de type `string[]` alors que dans le type `MinimalGodfatherPayload` il est de type `Category[]`. Jsp de quel côté faut que je gère ça dcp. Update le schéma pour que les catégories deviennent une énum pour avoir le bon typage ? ou avoir un string[] partout ?

2022-08-21 15:55 UTC, achille-bsc approved these changes

2022-08-21 16:00 UTC, achille-bsc commented on src/bot/commands/ignore.ts
> +    }
c'est vraiment obligé le deuxième check ?

2022-08-21 16:45 UTC, Swiizyy commented on src/bot/commands/ignore.ts
> +    }
Oui c'est pour check si le parrain est dans la db

2022-09-10 12:58 UTC, achille-bsc commented
Petite question, on en est où de cette pr ? elle est finie ou pas encore ?

2022-09-10 19:41 UTC, DraftProducts commented
J'ai demandé sur Discord :)

2022-11-07 23:37 UTC, achille-bsc commented on src/bot/commands/ignore.ts
> +  private static ActionButtonsMapping: Record<string, string> = {
Ça change quoi concrètement de déclarer en dehors du scope ?

2022-11-07 23:50 UTC, DraftProducts commented on src/bot/commands/ignore.ts
> +  private static ActionButtonsMapping: Record<string, string> = {
Ça ne sert à rien de surcharger la classe inutilement, c'est tout.

2022-11-08 00:34 UTC, achille-bsc approved these changes

2022-11-08 00:34 UTC, achille-bsc commented on src/bot/commands/ignore.ts
> +    while (true) {
Par contre chui pas tellement pour l'idée de le mettre dans le util, ça encombrerait pour quelque chose qui ne sera probablement pas réutilisé en dehors de cette fonctionnalité... donc je serais d'avis de créer un fichier de module à part... et si jamais on a besoin de le réutiliser on pourra toujours transférer le code dans util... mais bon, là, je pense que ça l'encombrerait juste pour rien 😕

2022-11-08 00:34 UTC, achille-bsc commented on src/bot/commands/ignore.ts
> +      } catch (e: unknown) {
```suggestion
      } catch (e) {
```

inutile de typer la variable e vu qu'elle n'est pas utilisée 🤔

2022-11-08 00:34 UTC, achille-bsc commented on src/bot/commands/ignore.ts
> +  private static ActionButtonsMapping: Record<string, string> = {
ah ok ! :)

2022-11-08 00:34 UTC, achille-bsc commented on src/bot/commands/ignore.ts
> +  private static ActionButtonsMapping: Record<string, string> = {
Ah mais ce que je viens de voir c'est que ça permet de mieux gérer la portée de la déclaration après... c'est pratique pour la réutiliser dans la fonction "generateMessageOptions"

2022-11-08 00:34 UTC, achille-bsc commented on src/bot/commands/ignore.ts
> +      godfather = await this.checkIsGodfather(interaction);
comme ça la variable "godfather" à le type "MinimalGodfatherPayload" alors que si on met un "isGodfather" le type de retour est booléen

2022-11-10 16:44 UTC, DraftProducts commented
Superseded by: #455

2022-11-10 16:45 UTC, closed without merging