Ajout d'une commande de suppression des blagues pour DraftMan
DraftProducts/blagues-api pull request #424
Opened 2022-08-31 10:33 UTC by MrPRAINGLE

L'idée est de ne plus supprimer des blagues à la main. C'est aussi l'occasion de récupérer un peu de code de la commande `/report` qui ne verra jamais le jour (RIP).

2022-09-08 01:49 UTC, Swiizyy requested changes
Quelques modifs notifié plus haut et je pense que se sera good.

GG a toi 👌

2022-09-08 01:49 UTC, Swiizyy commented on src/bot/commands/delete.ts
> +    if (interaction.user.id !== '207190782673813504') {
Oublie pas c'est de l'open source donc pas de userID comme ca :)

```suggestion
   if (interaction.user.id !== process.env.BOT_USER_OWNER) {
```

2022-09-08 01:49 UTC, Swiizyy commented on src/bot/commands/delete.ts
> +              style: ButtonStyle.Secondary
Sa serais pas mieux ? 🤔
```suggestion
      content: 'Voulez-vous vraiment supprimer la blague suivante ?',
      embeds: [embed],
      components: [
        {
          type: ComponentType.ActionRow,
          components: [
            {
              type: ComponentType.Button,
              label: 'Oui',
              customId: 'yes',
              style: ButtonStyle.Success
            },
            {
              type: ComponentType.Button,
              label: 'Non',
              customId: 'no',
              style: ButtonStyle.Danger
```

2022-09-08 01:49 UTC, Swiizyy commented on src/bot/commands/delete.ts
> +        content: "La blague n'a pas été envoyée.",
C'est pas bon le copié-coller 😶
```suggestion
        content: 'La suppression de la blague a bien été annulée.',
```

2022-09-08 01:49 UTC, Swiizyy commented on src/bot/commands/delete.ts
> +
Pourquoi pas le rajouté dans le logs nan ? 
```suggestion

    const logsChannel = interaction.client.channels.cache.get(logsChannelId) as TextChannel;

    if (isEmbedable(logsChannel)) {
      await logsChannel.send({
        content: "Blague retirée de l'API",
        embeds: [embed]
      });
    }

```

2022-09-08 01:49 UTC, Swiizyy commented on src/bot/commands/delete.ts
> +    if (!success) return;
Je serais quand même d'avis de renvoyé un message si il y'a un probleme 😕
```suggestion

if (!success) return confirmation.update(interactionProblem("La blague n'a pu être supprimée !", true));
```

2022-09-08 01:49 UTC, Swiizyy commented on src/bot/commands/delete.ts
> +    if (!success) return;
Je pense meme que sa serais pas mal comme ca . Vous en pensez quoi ?
```suggestion
const { success, error } = await Jokes.deleteJoke(joke);

    if (!success && error)
      return confirmation.update(interactionProblem(`La blague n'a pu être supprimée ! n\ Erreur: ${codeBlock(error)}`, true));
```
```suggestion
    const { success, error } = await Jokes.deleteJoke(joke);

    if (!success && error)
      return confirmation.update(
        interactionProblem(
          stripIndents`
             La blague n'a pu être supprimée !
             **Erreur:**
            ${codeBlock(error)}
          `,
          true
        )
      );
```

2022-09-08 01:49 UTC, Swiizyy commented on src/jokes.ts
> +      const toDelJoke = jokes.find((j) => j.id === joke.id)!;
Vaut mieux quand meme check si il y'a une blague ou pas au cas ou. 
```suggestion
      const toDelJoke = jokes.find((j) => j.id === joke.id);

      if (!toDelJoke) return { success: false, error: `La blague n'a pas été trouvée.` };

```

2022-09-08 01:49 UTC, Swiizyy commented on src/jokes.ts
> +        joke.id -= jIndex > index ? 1 : 0;
Tu peut direct le mettre sur une seul ligne :)
```suggestion
        joke.id -= jokes.findIndex((j) => j === joke) > index ? 1 : 0;
```

2022-09-08 16:17 UTC, MrPRAINGLE commented on src/bot/commands/delete.ts
> +    if (!success) return;
J'ai fait un petit truc pour améliorer.

2022-09-09 05:54 UTC, achille-bsc reviewed
Quelques changements qui ne sont pas indispensables à mon avis, mais qui seraient agréables

2022-09-09 05:54 UTC, achille-bsc commented on src/bot/commands/delete.ts
> +    if (interaction.user.id !== process.env.BOT_USER_OWNER) {
```suggestion
    if (interaction.user.id !== process.env.BOT_OWNER_ID) {
```
Je pense que ce serait plus clair de rénover la variable d'environnement BOT_OWNER_ID par ce que comme ça on peut facilement voir que c'est l'id de l'owner du bot... par ce que avant, c'était lisible, mais pas aussi clair je trouve

2022-09-09 05:54 UTC, achille-bsc commented on src/bot/commands/delete.ts
> +    interaction.client.refreshStatus();
Il faudrais le décaler pour le mettre à la toute fin des instructions, par ce que la tu refresh le statut avant d'enlever la blague de la db... donc c'est pas très utile...

2022-09-09 05:54 UTC, achille-bsc commented on src/jokes.ts
> +      const toDelJoke = jokes.find((j) => j.id === joke.id);
```suggestion
      const jokeToDelete = jokes.find((j) => j.id === joke.id);
```
Je pense que rénover la constante de cette manière serais plus clair, et correspondrait plus aux conventions respectes jusque là sur le projet je trouve 🤔

2022-09-09 12:21 UTC, Swiizyy commented on src/bot/commands/delete.ts
> +    interaction.client.refreshStatus();
Ah ouais, bien vu 👌

2022-09-09 12:21 UTC, Swiizyy commented on src/bot/commands/delete.ts
> +    if (interaction.user.id !== process.env.BOT_USER_OWNER) {
Je suis d'accord 👍

2022-09-09 13:39 UTC, MrPRAINGLE commented on src/bot/commands/delete.ts
> +    if (interaction.user.id !== process.env.BOT_USER_OWNER) {
Pas faux...

2022-09-09 13:39 UTC, MrPRAINGLE commented on src/bot/commands/delete.ts
> +    interaction.client.refreshStatus();
Bien vu

2022-09-09 13:40 UTC, MrPRAINGLE commented on src/jokes.ts
> +      const toDelJoke = jokes.find((j) => j.id === joke.id);
C'est vrai, à la base c'était une variable provisoire pour test, mais j'ai oublié de la renommer 😅

2022-09-09 13:40 UTC, MrPRAINGLE commented
Je fais tous les changements proposés ce soir !!

2022-09-10 09:15 UTC, DraftProducts requested changes

2022-09-10 09:15 UTC, DraftProducts commented on src/bot/commands/delete.ts
> +    }
Je préférerais que tu vérifies les permissions si la personne est admin ou non, tu peux dès lors définir la permission requise dans les contructor de la commande : https://discord.js.org/#/docs/main/main/typedef/ApplicationCommandData

2022-09-10 09:15 UTC, DraftProducts commented on src/bot/commands/delete.ts
> +          name: 'recherche',
```suggestion
          name: 'query',
```
toujours en anglais, tu peux ajouter `nameLocalizations` si tu veux qu'il soit affiché en français mais dans le code ça doit être en anglais.
https://discord.js.org/#/docs/main/main/typedef/ApplicationCommandData

2022-09-10 09:15 UTC, DraftProducts commented on src/bot/commands/delete.ts
> +    })) as Message<true>;
Type forcé non nécessaire

2022-09-10 09:15 UTC, DraftProducts commented on src/jokes.ts
> +      }
Pas possible de faire ça, les id sont synchronisés avec la base de donnée.
À la limite si tu veux, tu pourrais faire un système qui prend la dernière blague et qui la met à la place (et tu update en bdd la colonne joke_id)

2022-09-10 09:15 UTC, DraftProducts commented on src/jokes.ts
> +      const index = jokes.indexOf(jokeToDelete);
```suggestion

      const deleteIndex = jokes.findIndex((j) => j.id === joke.id);
      if (deleteIndex === -1) return { success: false, error: `La blague n'a pas été trouvée.` };
```

2022-09-10 09:15 UTC, DraftProducts commented on src/jokes.ts
> +      jokes.splice(index, 1);
```suggestion
      jokes.splice(deleteIndex, 1);
```

2022-09-10 09:15 UTC, DraftProducts commented on src/bot/commands/delete.ts
> +              ${codeBlock(error)}<
```suggestion
              ${codeBlock(error)}
```

2022-09-10 11:00 UTC, achille-bsc commented on src/bot/commands/delete.ts
> +          name: 'recherche',
Ouais, mais si on veut mettre les slashLocalization faudrais changer d'eux trois trucs dans le lib/command (sauf si j'ai loupé une pr) mais si c'est pas déjà fais, ça je pourais m'en occuper...

2022-09-11 12:57 UTC, DraftProducts requested changes

2022-09-11 12:57 UTC, DraftProducts commented on src/jokes.ts
> +      });
Dans un premier temps, je te propose d'utiliser directement, l'index, je t'ai fait un exemple dans la review précedente.
Ensuite, ce serait intéressant que la blague prenne la place de l'ancienne de sorte qu'elles soient quand même triés par ID.
Pour cela je te propose de faire directement un truc du style : 
```js
const [lastJoke] = jokes.splice(-1, 1);
jokes[deleteIndex] = { ...lastJoke, id: deleteIndex };
```
PS: je salue l'utilisation du `.at` très bonne initiative, ici je propose d'utiliser splice afin de directement supprimer l'élément 👍

2022-11-10 12:38 UTC, Swiizyy approved these changes

2022-11-10 13:29 UTC, merged