feat(bot): ✨ Change the Command class to  accept nameLocalization & descriptionLocalization
DraftProducts/blagues-api pull request #436
Opened 2022-09-12 04:29 UTC by achille-bsc

2022-09-12 04:32 UTC, achille-bsc commented
Salut ! j'ai un petit problème sur le l'intégration des nameLocalization (et des descriptionLocalization) c'est que pour les commandes de type CHAT_INPUT ça fonctionne parfaitement, mais celle de type MESSAGE, la traduction n'a pas lieux pour une raison qui m'est inconnue.... je vais continuer de chercher et tenter des trucs, mais si qqn à une idée, elle est la bienvenue 🥲

2022-09-12 07:46 UTC, DraftProducts commented
Commit déjà celles que tu as fait 👍

2022-09-12 07:48 UTC, DraftProducts requested changes
Je ne pense pas qu'ajouter descriptionLocalizations soit pertinent, le but n'est pas d'avoir un bot traduit, juste d'avoir des noms de commandes (qui sont aussi le nom des fichiers) en anglais.
Et d'avoir la possibilité de mettre des accents dans les noms des commandes (ce qui n'est possible que dans nameLocalization).

2022-09-12 07:48 UTC, DraftProducts commented on src/bot/lib/command.ts
> +    this.nameLocalization = data.nameLocalizations!;
Au même titre que descriptionLocalizations, je pense que tu peux le laisser dans le raw, il n'est jamais utile dans le code.
```suggestion
```

2022-09-12 07:52 UTC, achille-bsc commented
> Commit déjà celles que tu as fait 👍 

OK, je fais ça dès que je rentre ce soir 🙂

2022-09-13 09:34 UTC, Swiizyy requested changes
Quelque petites modifs à faire, faire la commande stats et sa sera nickel 👌

2022-09-13 09:34 UTC, Swiizyy commented on src/bot/lib/command.ts
> +  public nameLocalization: LocalizationMap | undefined;
```suggestion
```

2022-09-13 09:34 UTC, Swiizyy commented on src/bot/lib/command.ts
> +} from 'discord.js';
```suggestion
import { ApplicationCommandData, ApplicationCommandType, CommandInteraction, InteractionResponse } from 'discord.js';
```

2022-09-13 09:34 UTC, Swiizyy commented on src/bot/lib/command.ts
> +        nameLocalizations: this.nameLocalization,
```suggestion
        nameLocalizations: this.raw.nameLocalizations,
```

2022-09-13 09:34 UTC, Swiizyy commented on src/bot/commands/joke.ts
>            description: 'Aléatoire, Général, Développeur, Noir, +18, Beauf, Blondes',
```suggestion
          description: 'Type de blague',
```

2022-09-13 09:34 UTC, Swiizyy commented on src/bot/commands/correction.ts
> +      description: 'Propose une modification',
```suggestion
      description: 'Proposer une modification de blague/suggestion',
```

2022-09-13 09:34 UTC, Swiizyy commented on src/bot/commands/approve.ts
> +        fr: 'approuver'
```suggestion
        fr: 'Approuver'
```

2022-09-13 09:34 UTC, Swiizyy commented on src/bot/commands/disapprove.ts
> +        fr: 'désapprouver'
```suggestion
        fr: 'Désapprouver'
```

2022-09-13 09:34 UTC, Swiizyy commented on src/bot/commands/leaderboard.ts
>        description: 'Afficher les statistiques',
```suggestion
      description: 'Afficher les statistiques globales du serveur',
```

2022-09-13 09:38 UTC, DraftProducts commented on src/bot/commands/disapprove.ts
> +        fr: 'désapprouver'
Faudrait ajouter une majuscule au nom de base aussi 👍

2022-09-13 10:09 UTC, achille-bsc commented
> Quelque petites modifs à faire, faire la commande stats et sa sera nickel 👌

Ouais, mais il faut que Nicolas regarde par ce que pour une raison que j'ignore, les commande de type AplicationCommandType.MESSAGE ça les traduit pas... je comprends pas prq

2022-09-13 10:22 UTC, Swiizyy commented
> > Quelque petites modifs à faire, faire la commande stats et sa sera nickel 👌
> 
> Ouais, mais il faut que Nicolas regarde par ce que pour une raison que j'ignore, les commande de type AplicationCommandType.MESSAGE ça les traduit pas... je comprends pas prq

@achille-bsc Il te suffis de rajouter Ligne 39 dans le fichier Commands  `nameLocalizations: this.raw.nameLocalizations,`

2022-09-13 17:24 UTC, achille-bsc commented on src/bot/lib/command.ts
> +    this.nameLocalization = data.nameLocalizations!;
je ne comprends pas ce que tu veux dire par là ? 🤔 La raison pour la quelle je l'ai mis ici, c'est par ce que sinon  on à une erreur de typage  ligne 15 pour ce que il faudrais ajouter le type undefined de la façon suivante "public nameLocalization: LocalizationMap | undefined;"... en soit ça marche aussi... mais c'est pas hyper propre dans le cas ou on l'utilise dans chaque commande au final 🤷

2022-09-13 17:25 UTC, achille-bsc commented on src/bot/lib/command.ts
> +  public nameLocalization: LocalizationMap | undefined;
Pourquoi tu veux le retirer ?

2022-09-13 17:26 UTC, achille-bsc commented on src/bot/lib/command.ts
> +} from 'discord.js';
C'est prettier qui me l'a formaté comme ça.... donc autant le laisser dans le bon format... avant ça pouvais être sur une seul ligne, mais vu que j'avoute l'import de "LocalizationMap", ça rend la ligne d'import plus longue, et donc pour une meilleur lisibilité du code, ça me l'a formaté comme ça 🙃

2022-09-13 17:27 UTC, achille-bsc commented on src/bot/lib/command.ts
> +        nameLocalizations: this.nameLocalization,
t'es sur que ça marche si on fais comme ça ? attds je check la doc et je corrige si besoin dans la soirée ou demain 👍

2022-09-13 17:28 UTC, achille-bsc commented on src/bot/commands/joke.ts
>            description: 'Aléatoire, Général, Développeur, Noir, +18, Beauf, Blondes',
c'est pas le but de la PR 😉

2022-09-13 18:39 UTC, Swiizyy commented on src/bot/lib/command.ts
> +  public nameLocalization: LocalizationMap | undefined;
Tu n'en a pas l'utilité 👍

2022-09-13 18:40 UTC, Swiizyy commented on src/bot/lib/command.ts
> +} from 'discord.js';
Tu a pas l'utilité d'importer LocalizatioMap 🤷‍♂️

2022-09-13 18:41 UTC, Swiizyy commented on src/bot/lib/command.ts
> +        nameLocalizations: this.nameLocalization,
Oui c'est bien ça 👍

2022-09-13 18:41 UTC, Swiizyy commented on src/bot/commands/joke.ts
>            description: 'Aléatoire, Général, Développeur, Noir, +18, Beauf, Blondes',
Pas le but mais tu peut aussi 👍

2022-09-14 13:42 UTC, DraftProducts requested changes

2022-09-14 13:42 UTC, DraftProducts commented on src/bot/commands/correction.ts
> +      },
Aucun changement, tu peux donc le supprimer 👍 
```suggestion
```

2022-09-14 13:42 UTC, DraftProducts commented on src/bot/commands/joke.ts
> +          },
Pareil ici 
```suggestion
```

2022-09-14 13:42 UTC, DraftProducts commented on src/bot/commands/joke.ts
>            description: 'Aléatoire, Général, Développeur, Noir, +18, Beauf, Blondes',
Je suis pour le changement également 👍 
Pas besoin de faire une PR exprès pour ça,

2022-09-14 13:42 UTC, DraftProducts commented on src/bot/commands/leaderboard.ts
>        description: 'Afficher les statistiques',
Ici aussi 👍

2022-09-14 13:42 UTC, DraftProducts commented on src/bot/commands/userStats.ts
> +      name: 'statistics',
```suggestion
      name: 'Statistics',
```

2022-09-14 13:54 UTC, Swiizyy commented
Conventionnalcommit en PLS 👀

2022-09-15 02:00 UTC, Swiizyy approved these changes

2022-09-17 20:50 UTC, DraftProducts approved these changes

2022-09-17 21:04 UTC, achille-bsc commented
> Conventionnalcommit en PLS 👀 

😅😅😅

2022-09-18 12:56 UTC, merged