Changer la règle de vote d'une blague ayant une correction en cours
DraftProducts/blagues-api pull request #437
Opened 2022-09-12 09:13 UTC by Swiizyy

Closes #418

2022-09-12 09:50 UTC, DraftProducts requested changes
Le but est pas de supprimer ce système 🤔 juste d'accepter n'importe quel review de parrain (approvals et disapprovals)

2022-09-12 09:53 UTC, swiizyy commented
Beh justement c'est ça qui bloque l'approbation de la suggestion si il y'a une correction en cours 🧐

2022-09-12 09:54 UTC, Swiizyy commented
Dans se cas là il faudrait à la limite prévenir l'utilisateur qui y'a une correction en cours mais c'est déjà fait sur l'embed 🤷‍♂️

2022-09-12 12:31 UTC, DraftProducts commented
Le but est juste de demander à la personne d'approuver la correction avant d'approuver la suggestion nn ? 🤔

2022-09-13 09:36 UTC, Swiizyy commented
@MrPRAINGLE on est d'accord c'est bien sa que tu voulait faire ?

2022-09-13 09:40 UTC, DraftProducts commented
Il aurait juste suffit de faire : 
```
if (isSuggestion) {
      const correction = proposal.corrections[0];
      if (correction) {
        const beenApproved = correction.approvals.some((approval) => approval.user_id === interaction.user.id);
        const beenDisapproved = correction.disapprovals.some((disapproval) => disapproval.user_id === interaction.user.id);
        if (!beenApproved && !beenDisapproved) {
          const correctionLink = messageLink(correctionsChannelId, correction.message_id!, interaction.guild.id);
          const suggestionLink = messageLink(suggestionsChannelId, proposal.message_id!, interaction.guild.id);
          return interaction.reply(
            interactionInfo(
              `Il semblerait qu'une ${hyperlink(
                'correction aie été proposée',
                correctionLink
              )}, veuillez l'approuver avant l'approbation de ${hyperlink('cette suggestion', suggestionLink)}.`
            )
          );
        }
      }
    } else {
```

2022-09-13 09:44 UTC, Swiizyy commented
Je ne crois pas que ce sois sa qu'il voulait faire 🤔

2022-09-14 13:44 UTC, DraftProducts commented
Je vois pas ce qu'on pourrait faire d'autre, supprimer cette sécurité n'a pas de sens 🤔

2022-09-14 13:51 UTC, Swiizyy commented
Beh en tout cas c'est ce que j'ai compris de l'issue de Pringle 🤷‍♂️

2022-11-08 13:50 UTC, achille-bsc commented
Chui d'accord avec Nicolas, c'est mieux de faire colle ça, par ce que comme ça pour approuver une blague, la correction sera également approuvé ou désapprouve... ça me semble logique de faire comme ça...

2022-11-10 17:34 UTC, merged