joke auto publication
DraftProducts/blagues-api pull request #450
Opened 2022-11-08 18:13 UTC by achille-bsc

Auto publication des blagues sur GitHub

2022-11-09 13:50 UTC, Swiizyy approved these changes

2022-11-09 13:50 UTC, Swiizyy commented on src/bot/index.ts
> +  }
Personnellement je ne l'aurais pas mis là mais dans une classe comme pour les autres modules 👀
Tu en pense quoi ?

2022-11-09 13:50 UTC, Swiizyy commented on src/bot/modules/push.ts
> +}
J'aurais plutôt mis sa dans le dossier lib 👀

2022-11-09 15:02 UTC, DraftProducts commented on src/bot/modules/push.ts
> +}
Je suis d'accord 👍

2022-11-09 15:03 UTC, DraftProducts commented on src/bot/index.ts
> +  }
Oui 👍

2022-11-09 15:17 UTC, DraftProducts requested changes
Avant de commit tes fichiers, pense à bien vérifier que tu es d'accord avec tous les changements que tu vas apporter.
- Là, je vois que tu as changé tous les liens des dépendances dans le fichier `yarn.lock`.
- Que tu aies commit des changements qui n'étaient pas du ressort de cette PR (et qui sont d'ailleurs déjà dans la codebase).
- Le reformatage des fichiers de config ect...
- Tous les commentaires de tests sont à enlever avant tes commits
- Si tu souhaites justifier un changement comme le continue par exemple, fait le dans la PR, mais pas dans le code.

Je suis d'accord avec ce qu'a proposé @Swiizyy 👍 
Certaines parties du code ne sont pas à la bonne place.

2022-11-09 15:17 UTC, DraftProducts commented on .env.example
> +GITHUB_API_TOKEN=
Entre `JOKES_AUTO_PUBLICATION` et `SENTRY_DSN` avec un retour a la ligne de chaque coté

2022-11-09 15:17 UTC, DraftProducts commented on .vscode/settings.json
> +}
Je ne comprends pas pourquoi tu rechanges ça à chaque fois, c'est formaté à partir des règles du projet, essayes de régler le conflit dans ta config personnelle ou ne commit pas ce fichier s'il te plait.

2022-11-09 15:17 UTC, DraftProducts commented on src/bot/commands/approve.ts
> +      },
Pourquoi a-t-on ces changements de nouveau ? Ces changements n'ont aucun lien avec la PR et ont été merge d'une autre PR, il y a déjà un moment.

2022-11-09 15:17 UTC, DraftProducts commented on src/bot/index.ts
> +          // Je remet le continue par ce que sinon ya une erreur entre prettier et eslint
```suggestion
```

2022-11-09 15:17 UTC, DraftProducts commented on src/bot/index.ts
> +    }
```suggestion
    if (process.env.JOKES_AUTO_PUBLICATION === 'true') {
      // At 00:00 on Monday
      schedule.scheduleJob('0 0 * * 1', this.runGitPush);
    } else {
      console.log('Service d'auto-publication des blagues sur GitHub désactivé');
    }
```

2022-11-09 16:27 UTC, DraftProducts commented
Je viens de réécrire l'historique pour que tu repartes d'une bonne base :)
Pense juste à pull et après, tu peux commencer à corriger, à apporter les modifications de la review

2022-11-09 19:59 UTC, ErwanGit requested changes

2022-11-09 19:59 UTC, ErwanGit commented on src/bot/index.ts
> +        ...interactionProblem(`L'erreur suivante est survenur: \`\`\`${error}\`\`\``)
```suggestion
        ...interactionProblem(`Une erreur suivante est survenue : \`\`\`${error}\`\`\``)
```

2022-11-09 22:35 UTC, achille-bsc commented on src/bot/index.ts
> +        ...interactionProblem(`L'erreur suivante est survenur: \`\`\`${error}\`\`\``)
Ah bon ? ça me surprend un peu... ça ne me parait pas vraiment correct comme phrase, si ? Ça fait un peu bizarre à lire, je trouve, non ?

2022-11-09 22:57 UTC, DraftProducts requested changes
Regarde le module dans `reminders.ts`, il faudrait que ça ait cette forme, ça permettrait d'enlever le `node-schedule` du fichier index du bot.

2022-11-10 09:33 UTC, achille-bsc commented
> Regarde le module dans `reminders.ts`, il faudrait que ça ait cette forme, ça permettrait d'enlever le `node-schedule` du fichier index du bot.

Je ne suis paq sur de savoir ce que tu veux dire par là 😅

2022-11-10 10:00 UTC, DraftProducts commented
> > Regarde le module dans `reminders.ts`, il faudrait que ça ait cette forme, ça permettrait d'enlever le `node-schedule` du fichier index du bot.
> 
> Je ne suis paq sur de savoir ce que tu veux dire par là 😅

Une class avec un start du cron dans le constructor

2022-11-10 12:34 UTC, Swiizyy commented
> > Regarde le module dans `reminders.ts`, il faudrait que ça ait cette forme, ça permettrait d'enlever le `node-schedule` du fichier index du bot.
> 
> Je ne suis paq sur de savoir ce que tu veux dire par là 😅

Comme ceci :)


```ts
// AutoPublish.ts
import { Client } from 'discord.js';
import schedule from 'node-schedule';

export default class Reminders {
  public client: Client;

  constructor(client: Client) {
    this.client = client;

    if (process.env.JOKES_AUTO_PUBLICATION === 'false') return;

    // Every 10 minutes
    schedule.scheduleJob('0 0 * * 1', () => this.run());
  }

  async run(date: Date): Promise<void> {
    // Ajouter le code de ta fonction runGitPush
  }
}
```
```ts
// index.ts
import AutoPublish from './modules/autoPublish';

export default class Bot extends Client {
  public autoPublish: AutoPublish
  constructor() {
    this.autoPublish = new AutoPublish(this)
  }
}
```

2022-11-10 14:53 UTC, Swiizyy requested changes

2022-11-10 14:53 UTC, swiizyy commented on src/bot/modules/autoPublication.ts
> +    const channel = bot.channels.cache.get(process.env.LOGS_CHANNEL!) as TextChannel;
Est tu sur de vouloir recevoir le message d'erreur avec tout les autres logs ?
J'aurais plutot vu un DM a DraftMan pour ce cas de figure :)

2022-11-10 14:53 UTC, swiizyy commented on src/bot/modules/autoPublication.ts
> +      mergeBranch: 'test'
```suggestion
      mergeBranch: 'chore/autopublish-jokes'
```

2022-11-10 14:53 UTC, swiizyy commented on src/bot/modules/autoPublication.ts
> +  console.log('Push lancée avec succès !');
```suggestion
```

2022-11-10 15:04 UTC, achille-bsc commented on src/bot/modules/autoPublication.ts
> +    const channel = bot.channels.cache.get(process.env.LOGS_CHANNEL!) as TextChannel;
Non, par ce que en cas d'erreur, il pourrait être spam en mp, ce qui ne serait pas désirable... alors que les logs sont plus aptes à recevoir des erreurs

2022-11-10 15:56 UTC, Swiizyy commented on src/bot/modules/autoPublication.ts
> +    const channel = bot.channels.cache.get(process.env.LOGS_CHANNEL!) as TextChannel;
Non pas du tout c'est dans un try catch donc il serra avertie une seul fois nan ? 🧐

2022-11-10 16:26 UTC, achille-bsc commented on src/bot/modules/autoPublication.ts
> +    const channel = bot.channels.cache.get(process.env.LOGS_CHANNEL!) as TextChannel;
Bah nan, un try catch n'arrête pas le code, ça permet justement de gérer une erreur sans faire crash le programme, donc il y a toujours la possibilité que ça refasse la même erreur plus tard je crois

2022-11-10 21:43 UTC, ErwanGit requested changes

2022-11-10 21:43 UTC, ErwanGit commented on src/bot/index.ts
> +      console.log('Auto publication des blagues sur gitHub désactivé !');
```suggestion
      console.log('Auto-publication des blagues sur GitHub désactivée');
```

2022-11-10 21:43 UTC, ErwanGit commented on src/bot/modules/autoPublication.ts
> +      ...interactionProblem(`L'erreur suivante est survenur: \`\`\`${error}\`\`\``)
```suggestion
      ...interactionProblem(`L'erreur suivante est survenue : \`\`\`${error}\`\`\``)
```

2022-11-11 19:40 UTC, DraftProducts commented on src/bot/modules/autoPublication.ts
> +    const channel = bot.channels.cache.get(process.env.LOGS_CHANNEL!) as TextChannel;
Je serais plus pour qu'on envoie ce genre de message dans la console 🤔 
un simple `console.error` suffirait.

2022-11-11 19:45 UTC, ErwanGit approved these changes

2022-11-11 20:07 UTC, DraftProducts commented
> Comme ceci :)
> 
> ```ts
> // AutoPublish.ts
> import { Client } from 'discord.js';
> import schedule from 'node-schedule';
> 
> export default class Reminders {
>   public client: Client;
> 
>   constructor(client: Client) {
>     this.client = client;
> 
>     if (process.env.JOKES_AUTO_PUBLICATION === 'false') return console.log('Service d\'auto-publication des blagues sur GitHub désactivé');
> 
>     // Every 10 minutes
>     schedule.scheduleJob('0 0 * * 1', () => this.run());
>   }
> 
>   async run(date: Date): Promise<void> {
>     // Ajouter le code de ta fonction runGitPush
>   }
> }
> ```
> 
> ```ts
> // index.ts
> import AutoPublish from './modules/autoPublish';
> 
> export default class Bot extends Client {
>   public autoPublish: AutoPublish
>   constructor() {
>     this.autoPublish = new AutoPublish(this)
>   }
> }
> ```

👍

2022-11-11 23:15 UTC, DraftProducts approved these changes
Très beau boulot et très bonnes initiatives mais même si @achille-bsc mettait du temps j'aurais préféré que tu lui laisses s'en occuper étant donné que c'était sa PR (sauf si tu as eu son accord au préalable).

2022-11-11 23:15 UTC, DraftProducts commented on src/bot/index.ts
> +    });
Bonne idée mais je serais plus pour l'avoir dans le module directement pour éviter de surcharger ce fichier.

2022-11-11 23:28 UTC, Swiizyy commented on src/bot/index.ts
> +    });
J'ai vachement hésité sur se coup la mais oui tu a totalement raison :)

2022-11-12 08:24 UTC, achille-bsc commented
> Très beau boulot et très bonnes initiatives mais même si @achille-bsc mettait du temps j'aurais préféré que tu lui laisses s'en occuper étant donné que c'était sa PR (sauf si tu as eu son accord au préalable).

Il a effectivement eu mon accord au préalable ;) sinon je m'en serait occupé cet aprem, mais au moins c'est fait !
D'ailleurs je tien à m'excuser pour le temps que je vous ai tous fais perdre en n'ayant pas relu mon code ! J'ai retenu la leçon et ferait mieux la prochaine fois !

2022-11-12 10:37 UTC, DraftProducts commented
Pour moi tu peux merge 🔥 @Swiizyy

2022-11-12 11:04 UTC, Swiizyy commented
J'ai juste une petite suggestion avant de merge @DraftProducts :)

Une petite commande pour que tu puisse merge les blagues au cas ou avant le dimanche serait intéressant ou pas  ?

2022-11-12 11:14 UTC, Swiizyy approved these changes

2022-11-12 12:30 UTC, DraftProducts requested changes
Très bonne idée et super boulot gg ! 🔥

2022-11-12 12:30 UTC, DraftProducts commented on src/bot/modules/autoPublication.ts
> +      console.error('[Auto-Publish] La publication des blagues sur Github ou le point de terminaison a été spammé. !')
```suggestion
    '201': () => console.log('[Auto-Publish] Publication des blagues sur Github effectuée avec succès !'),
    '204': () => console.log('[Auto-Publish] Publication des blagues sur Github déjà effectuée !'),
    '403': () =>
      console.log(
        `[Auto-Publish] Permission d'accès manquante au repo "${this.options.owner}/${this.options.repo}"`
      ),
    '404': () => console.error(`[Auto-Publish] Branche "${this.options.baseBranch}" introuvable !`),
    '409': () => {
      this.octokit.pulls.create({
        owner: this.options.owner,
        repo: this.options.repo,
        title: "[Blagues] Conflit lors de l'ajout des dernières blagues",
        head: this.options.mergeBranch,
        base: this.options.baseBranch,
        body: stripIndents`
          ⚠️ Conflit détectée lors de l'ajout des dernières blagues !

          Veuillez résoudre ces conflits afin de fusionner la branche manuellement :)
        `,
        maintainer_can_modify: true
      });
      console.error(
        `[Auto-Publish] Conflit détecté lors de la publication des blagues sur Github !\n Une Pull-Request a été créée.`
      );
    },
    '422': () =>
      console.error('[Auto-Publish] Un ratelimit est survenu, la publication des blagues sur Github a été reportée à dimanche prochain !')
```

2022-11-12 12:30 UTC, DraftProducts commented on src/bot/modules/autoPublication.ts
> +      base: `${this.options.baseBranch}`,
```suggestion
      base: this.options.baseBranch,
```

2022-11-12 12:36 UTC, Swiizyy commented
> Très bonne idée et super boulot gg ! 🔥 

Merci 😁

2022-11-12 12:37 UTC, DraftProducts commented
Eeeeh

2022-11-12 12:37 UTC, DraftProducts commented
Kesissépassé ? @Swiizyy

2022-11-12 12:38 UTC, Swiizyy commented
> Kesissépassé ? @Swiizyy

Oupssi j'etait sur tel mdr :)

2022-11-12 12:45 UTC, merged

2022-11-12 22:19 UTC, achille-bsc commented on src/bot/commands/userStats.ts
> +import { Stats } from '../modules/stats';
```suggestion
import { Stats } from '../modules';
```
ce serait bien de faire cette petite modif dans tout les fichiers qui demande ce fichier