Dev
DraftProducts/blagues-api pull request #456
Opened 2022-11-11 22:57 UTC by MrPRAINGLE

Issue: #425

Cette PR sert à ajouter la recherche par mot-clé à la commande `/joke`.

2022-11-11 23:23 UTC, DraftProducts requested changes

2022-11-11 23:23 UTC, DraftProducts commented on src/bot/commands/joke.ts
> +          required: false
Pas besoin de le mettre si c'est false

2022-11-11 23:23 UTC, DraftProducts commented on src/bot/commands/joke.ts
> +          name: 'keyword',
```suggestion
          name: 'search',
```

2022-11-11 23:23 UTC, DraftProducts commented on src/bot/commands/joke.ts
> +            fr: 'mot-clé'
```suggestion
            fr: 'recherche'
```

2022-11-11 23:23 UTC, DraftProducts commented on src/bot/commands/joke.ts
> +      ? jokeByQuestion(jokeString.split('|')[0])!
Je ne suis pas fan, je préférais que la blague soit récupéré par son ID, ce serait possible ?

2022-11-12 15:32 UTC, Swiizyy commented
J'aime bien l'idée ! 🙂

Pourrais t'on pas faire une route pour en faire profiter tout le monde ? 🧐

2022-11-12 22:26 UTC, achille-bsc approved these changes

2022-11-13 21:27 UTC, swiizyy commented on src/bot/commands/joke.ts
> +      ).ratings
Se serais pas mieux un includes ?
Car je pense que le findBestMatch est actuellement un peut vague et ne donne parfois pas se qu'on le souhaite ...
Vous en pensez quoi ? 🧐

2022-11-14 14:03 UTC, DraftProducts requested changes

2022-11-14 14:03 UTC, DraftProducts commented on src/bot/commands/joke.ts
> +    const joke = jokeString
faudrait rajouter une sécurité pour quand joke est = null

PS: Faudrait enlever le `!` après le jokeById

2022-11-14 14:04 UTC, DraftProducts commented
> J'aime bien l'idée ! 🙂
> 
> Pourrais t'on pas faire une route pour en faire profiter tout le monde ? 🧐 Si oui, pk pas passer par cette route pour la récupérer 🙂

Oui j'aime bien l'idée

2022-11-26 13:21 UTC, DraftProducts requested changes

2022-11-26 13:39 UTC, DraftProducts requested changes

2022-11-26 13:39 UTC, DraftProducts commented on src/controllers.ts
> +export function JokesByKeyword(key: string, type?: string | string[]) {
```suggestion
export function jokesByKeyword(key: string, type?: string | string[]) {
```

2022-11-26 13:39 UTC, DraftProducts commented on src/controllers.ts
> +  return word.filter((word: string) => compareTwoStrings(word, key.toLowerCase()) > 0.95).length !== 0;
```suggestion
  return word.filter((word) => compareTwoStrings(word, key.toLowerCase()) > 0.95).length !== 0;
```

2022-11-26 13:39 UTC, DraftProducts commented on src/bot/commands/joke.ts
> +      const possiblesJoke = JokesByKeyword(keyword);
```suggestion
      const possiblesJokes = JokesByKeyword(keyword);
```

2022-11-26 13:39 UTC, DraftProducts commented on src/bot/commands/joke.ts
> +    const keyword = interaction.options.getString('search');
```suggestion
    const search = interaction.options.getString('search');
```

2022-11-26 13:39 UTC, DraftProducts commented on src/controllers.ts
> +  const response = jokeById(joke.id);
```suggestion
  const response = random(JokesByKeyword(key, type));
```

2022-11-26 13:51 UTC, DraftProducts requested changes

2022-11-26 13:51 UTC, DraftProducts commented on src/bot/commands/joke.ts
> +      const possiblesJoke = JokesByKeyword(keyword);
```suggestion
      const availableJokes = JokesByKeyword(keyword);
```

2022-11-26 15:26 UTC, DraftProducts approved these changes

2022-11-27 23:36 UTC, DraftProducts approved these changes

2022-12-01 11:07 UTC, merged